// server.idl

module MainClient {
    interface Client {
        
    boolean return_status(); //Trocar por uma variavel depois
	void receive_msg(in string sender, in string receiver, in string msg, in string timestamp); 
	void update_contacts_status(in string user_name, in boolean new_status);
	
    };   
};