// server.idl

module MainServer {
    interface Server {

	void receive_username(in string user_name);
	void send_msg(in string sender, in string receiver, in string msg, in string timestamp);
	void send_status(in string user_name, in boolean new_status);
		
	boolean username_is_registered(in string username); 
    };   
};