# DO NOT EDIT THIS FILE!
#
# Python module Agenda generated by omniidl

import omniORB
omniORB.updateModule("Agenda")

# ** 1. Stub files contributing to this module
import schedule_idl

# ** 2. Sub-modules

# ** 3. End
