#:kivy 1.10
<LoginScreen>:
   BoxLayout:
      orientation:'vertical'
      Label:
            text: 'I am LoginScreen'
      Label:
            id: lbl1
      Button:
            text: 'Read'
            on_press: root.press_read()
      Button:
            text: 'Change'
            on_press:
               app.MY_NUMBER = app.MY_NUMBER + 1
               root.ids.lbl1.text = 'SharedVar is ' + str(app.MY_NUMBER)
      Button:
            text: 'Go to ScreenTwo'
            on_press: app.sm.current = "screen_2"
<MenuScreen>:
   BoxLayout:
      orientation:'vertical'
      Label:
            text: 'I am MenuScreen'
      Label:
            id: lbl2
      Button:
            text: 'Read'
            on_press: root.press_read()
      Button:
            text: 'Change'
            on_press: 
               app.MY_NUMBER = app.MY_NUMBER + 1
               root.ids.lbl2.text = 'SharedVar is ' + str(app.MY_NUMBER)
      Button:
            text: 'Go to ScreenOne'
            on_press: app.sm.current = "screen_1"