# DO NOT EDIT THIS FILE!
#
# Python module MainServer generated by omniidl

import omniORB
omniORB.updateModule("MainServer")

# ** 1. Stub files contributing to this module
import server_idl

# ** 2. Sub-modules

# ** 3. End
